---
deployment:
  tasks:
  - /usr/local/bin/php composer.phar install --no-dev
  - export DEPLOYPATH=/home1/denyconf/public_html/
  - /bin/cp -R dist $DEPLOYPATH
  - /bin/cp -R vendor $DEPLOYPATH
  - /bin/cp index.php $DEPLOYPATH
  - /bin/cp .htaccess $DEPLOYPATH
