# This will spin up a non-free AppEngine service!
# Use this to deploy the frontend as the default AppEngine service.

runtime: python37
# env: flex
entrypoint: gunicorn -b :$PORT frontend:app

env_variables:
  environment: "--prod"
  PROD: "true"
  DB_HOST: "162.241.24.146"
  DB_NAME: "denyconf_2020"
  DB_USER: "denyconf_webby"

handlers:

- url: /dist/(.*)
  static_files: dist/\1
  upload: dist/.*
- url: /favicon.ico
  static_files: dist/assets/favicon.ico
  upload: dist/assets/favicon.ico
- url: /.*
  script: auto
