runtime: python37

# instance_class: F2
# service: server

env_variables:
  DB_HOST: "/cloudsql/denyconformity:us-central1:denyconformity"
  DB_NAME: "denyconformity"
  DB_USER: "web"
  # DJANGO_SETTINGS_MODULE: 'denyconformity.settings'

handlers:
- url: /.*
  script: auto

- url: /static
  static_dir: static
